/**
 * This file was generated by the Jeddict
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author aluno
 */
@Entity
public class Cadastro {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column
    private String cnpfFranquia;

    @Column
    private String nomeFantasiaFranq;

    @Column
    private String razaosocialFranquia;

    @Column
    private String fiador;

    @Column
    private String cnpfFranquiado;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCnpfFranquia() {
        return this.cnpfFranquia;
    }

    public void setCnpfFranquia(String cnpfFranquia) {
        this.cnpfFranquia = cnpfFranquia;
    }

    public String getNomeFantasiaFranq() {
        return this.nomeFantasiaFranq;
    }

    public void setNomeFantasiaFranq(String nomeFantasiaFranq) {
        this.nomeFantasiaFranq = nomeFantasiaFranq;
    }

    public String getRazaosocialFranquia() {
        return this.razaosocialFranquia;
    }

    public void setRazaosocialFranquia(String razaosocialFranquia) {
        this.razaosocialFranquia = razaosocialFranquia;
    }

    public String getFiador() {
        return this.fiador;
    }

    public void setFiador(String fiador) {
        this.fiador = fiador;
    }

    public String getCnpfFranquiado() {
        return this.cnpfFranquiado;
    }

    public void setCnpfFranquiado(String cnpfFranquiado) {
        this.cnpfFranquiado = cnpfFranquiado;
    }

}
