/**
 * This file was generated by the Jeddict
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * @author aluno
 */
@Entity
public class Franquia {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column
    private long cnpj;

    @Column
    private String nomefantasia;

    @Column
    private float valorminimo;

    @Column
    private float captaldegirominimo;

    @Column
    private String ramo;

    @OneToOne(targetEntity = Cadastro.class)
    private Cadastro cadastro;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getCnpj() {
        return this.cnpj;
    }

    public void setCnpj(long cnpj) {
        this.cnpj = cnpj;
    }

    public String getNomefantasia() {
        return this.nomefantasia;
    }

    public void setNomefantasia(String nomefantasia) {
        this.nomefantasia = nomefantasia;
    }

    public float getValorminimo() {
        return this.valorminimo;
    }

    public void setValorminimo(float valorminimo) {
        this.valorminimo = valorminimo;
    }

    public float getCaptaldegirominimo() {
        return this.captaldegirominimo;
    }

    public void setCaptaldegirominimo(float captaldegirominimo) {
        this.captaldegirominimo = captaldegirominimo;
    }

    public String getRamo() {
        return this.ramo;
    }

    public void setRamo(String ramo) {
        this.ramo = ramo;
    }

    public Cadastro getCadastro() {
        return this.cadastro;
    }

    public void setCadastro(Cadastro cadastro) {
        this.cadastro = cadastro;
    }

}
