/**
 * This file was generated by the Jeddict
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * @author aluno
 */
@Entity
public class Imovel {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column
    private Boolean localVistoriado;

    @Column
    private Boolean pesquisaDeMercado;

    @Column
    private boolean imovelPropio;

    @OneToOne(targetEntity = Franquia.class)
    private Franquia franquia;

    @ManyToOne(targetEntity = FichaDeSelecao.class)
    private FichaDeSelecao fichaDeSelecao;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean isLocalVistoriado() {
        return this.localVistoriado;
    }

    public void setLocalVistoriado(Boolean localVistoriado) {
        this.localVistoriado = localVistoriado;
    }

    public Boolean isPesquisaDeMercado() {
        return this.pesquisaDeMercado;
    }

    public void setPesquisaDeMercado(Boolean pesquisaDeMercado) {
        this.pesquisaDeMercado = pesquisaDeMercado;
    }

    public boolean isImovelPropio() {
        return this.imovelPropio;
    }

    public void setImovelPropio(boolean imovelPropio) {
        this.imovelPropio = imovelPropio;
    }

    public Franquia getFranquia() {
        return this.franquia;
    }

    public void setFranquia(Franquia franquia) {
        this.franquia = franquia;
    }

    public FichaDeSelecao getFichaDeSelecao() {
        return this.fichaDeSelecao;
    }

    public void setFichaDeSelecao(FichaDeSelecao fichaDeSelecao) {
        this.fichaDeSelecao = fichaDeSelecao;
    }

}
