/**
 * This file was generated by the Jeddict
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * @author aluno
 */
@Entity
public class PesquisaDeMercado {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column
    private boolean localViavel;

    @Column
    private String InteresseDoPublico;

    @Column
    private String PrevisaoDeRetorno;

    @Column
    private boolean abalaComerciosProximos;

    @Column
    private String meioAmbiente;

    @OneToOne(targetEntity = Imovel.class)
    private Imovel imovel;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean isLocalViavel() {
        return this.localViavel;
    }

    public void setLocalViavel(boolean localViavel) {
        this.localViavel = localViavel;
    }

    public String getInteresseDoPublico() {
        return this.InteresseDoPublico;
    }

    public void setInteresseDoPublico(String InteresseDoPublico) {
        this.InteresseDoPublico = InteresseDoPublico;
    }

    public String getPrevisaoDeRetorno() {
        return this.PrevisaoDeRetorno;
    }

    public void setPrevisaoDeRetorno(String PrevisaoDeRetorno) {
        this.PrevisaoDeRetorno = PrevisaoDeRetorno;
    }

    public boolean isAbalaComerciosProximos() {
        return this.abalaComerciosProximos;
    }

    public void setAbalaComerciosProximos(boolean abalaComerciosProximos) {
        this.abalaComerciosProximos = abalaComerciosProximos;
    }

    public String getMeioAmbiente() {
        return this.meioAmbiente;
    }

    public void setMeioAmbiente(String meioAmbiente) {
        this.meioAmbiente = meioAmbiente;
    }

    public Imovel getImovel() {
        return this.imovel;
    }

    public void setImovel(Imovel imovel) {
        this.imovel = imovel;
    }

}
